### ISSUE TITLE
Fail to install tysserand

### ISSUE THREAD

**Issue by maulakhan** [VeraPancaldiLab/tysserand#2]
Hello, 
I am trying to use the installation instructions provided by you. I am using cmd on windows 10 to create a new environment for tysserand as you suggested (and since direct  `pip install tysserand` also doesn't work). However, with mamba, I am getting this error:

C:\Users\akhan>mamba env create --file environment.yml
Traceback (most recent call last):
  File "C:\Users\akhan\Miniconda3\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\akhan\Miniconda3\lib\site-packages\mamba\mamba.py", line 49, in <module>
    from mamba import repoquery as repoquery_api
  File "C:\Users\akhan\Miniconda3\lib\site-packages\mamba\repoquery.py", line 12, in <module>
    def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'

And with pyenv, I am getting this:

C:\Users\akhan>pyenv virtualenv 3.8.10 spatial-networks
pyenv: no such command 'virtualenv'

Can you please guide me on how to install tysserand on windows 10?

Best,
Arif

**Comment by AlexCoul** [comment]
Hi Arif,
Thank you very much for your feedback, this issue is critical.
Indeed I had an error while installing tysserand v0.5.1 with `pip install tysserand`, it's actually due to adding the `pathlib` library in the .toml file whereas it wasn't required, but now I have issues with poetry to update the .lock file and to do a successful installation.
However the `requirements.txt' file is correct, so we can install it following these steps:
1. download the repository with `git clone https://github.com/VeraPancaldiLab/tysserand.git`
2. go in the repo with `cd tysserand`
3. install dependencies with `pip install -r requirements.txt`
4. install tysserand from the local repo with `python setup.py install`

And tysserand should be up and running :-)
If it doesn't work keep me updated, in the meantime I'll try to fix this poetry issue, that's not the first time it happens and I'll probably have change environment manager, I have already lost hours during my postdoc with poetry :-/

**Comment by AlexCoul** [comment]
Hi Arif,
I realize that your installation issue was different from what I was getting, and I had an issue just because of my fuzzy internet connection. Your trouble seemed to come from a more general question about how to create a new environment, is it right?
If that's the case, to use pyenv and virtualenv (my preferred method, for several reason details in various blogposts):
```bash
# install necessary compilation tools
sudo apt-get update; sudo apt-get install make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
# from https://github.com/pyenv/pyenv-installer:
curl https://pyenv.run | bash
# then follow instructions to add environment variables to ~/.profile and ~/.bashrc, and source them
#in ~/.profile:
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
#and this in ~/.bashrc:
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# As the pyenv init output also says, you need to fully log out of your session and back in for changes to ~/.profile to take effect (because this file is parsed by your GUI manager (or login shell) at session startup).

# install a Python version
pyenv install --list | grep " 3\."
pyenv install 3.8.10
# setting up default python version for the system and per folder:
pyenv shell 3.8.10
pyenv global 3.8.10
cd ~/path/to/Projects/
pyenv local 3.8.10 
```

Does it answer your question?

Best,
Alexis

**Comment by AlexCoul** [comment]
So I believe tysserand installs correctly, I had tested it on several different machines, I'm closing this issue.
